name: postgres
description: PostgreSQL relational database for persistent data storage
category: database
version: "15"

# Default configuration
defaults:
  image: postgres:15-alpine
  port: 5432
  database: local_dev
  username: postgres
  password: password

# Environment variables this service provides
environment:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
  POSTGRES_DB: "${POSTGRES_DB:-local_dev}"
  POSTGRES_USER: "${POSTGRES_USER:-postgres}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
  POSTGRES_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@localhost:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-local_dev}"
  DATABASE_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@localhost:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-local_dev}"

# Docker-specific configuration
docker:
  restart: unless-stopped
  command: >
    postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c log_statement=all
      -c log_destination=stderr
      -c log_min_duration_statement=100ms
  networks:
    - dev-stack
  memory_limit: 512m
  environment:
    - POSTGRES_DB=${POSTGRES_DB:-local_dev}
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
  health_check:
    test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-local_dev}"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 30s

# Spring Boot configuration
spring_config:
  properties:
    - "spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-local_dev}"
    - "spring.datasource.username=${POSTGRES_USER:-postgres}"
    - "spring.datasource.password=${POSTGRES_PASSWORD:-password}"
    - "spring.datasource.driver-class-name=org.postgresql.Driver"
    - "spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect"
    - "spring.jpa.hibernate.ddl-auto=validate"
    - "spring.jpa.show-sql=true"
    - "spring.jpa.properties.hibernate.format_sql=true"

# Dependencies
dependencies: []

# Ports that need to be available
required_ports:
  - "${POSTGRES_PORT:-5432}"

# Volume mounts
volumes:
  - name: postgres-data
    mount: /var/lib/postgresql/data
    description: PostgreSQL data directory

# Documentation links
docs:
  - name: PostgreSQL Documentation
    url: https://www.postgresql.org/docs/
  - name: Spring Data JPA
    url: https://docs.spring.io/spring-data/jpa/docs/current/reference/html/

# Common use cases
use_cases:
  - Primary application database
  - Transactional data storage
  - Relational data modeling
  - ACID compliance requirements
