title = "dev-stack Documentation"
baseURL = "/"
languageCode = "en-US"
theme = "doks"

# Site settings
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
disableAliases = true
disableHugoGeneratorInject = true
rssLimit = 10
summarylength = 20

# Content settings
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Main sections
mainSections = ["docs"]
