name: mysql
description: MySQL relational database for persistent data storage
category: database
version: "8"

# Default configuration
defaults:
  image: mysql:8-oracle
  port: 3306
  database: local_dev
  username: root
  password: password
  memory_limit: 512m
  persistence: true
  log_slow_queries: true

# Environment variables this service provides
environment:
  MYSQL_HOST: localhost
  MYSQL_PORT: "${MYSQL_PORT:-3306}"
  MYSQL_DATABASE: "${MYSQL_DATABASE:-local_dev}"
  MYSQL_USER: "${MYSQL_USER:-root}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
  MYSQL_URL: "mysql://${MYSQL_USER:-root}:${MYSQL_PASSWORD:-password}@localhost:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-local_dev}"
  DATABASE_URL: "mysql://${MYSQL_USER:-root}:${MYSQL_PASSWORD:-password}@localhost:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-local_dev}"

# Spring Boot configuration
spring_config:
  properties:
    - "spring.datasource.url=jdbc:mysql://localhost:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-local_dev}?useSSL=false&serverTimezone=UTC"
    - "spring.datasource.username=${MYSQL_USER:-root}"
    - "spring.datasource.password=${MYSQL_PASSWORD:-password}"
    - "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver"
    - "spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect"
    - "spring.jpa.hibernate.ddl-auto=validate"
    - "spring.jpa.show-sql=true"
    - "spring.jpa.properties.hibernate.format_sql=true"
  yaml: |
    spring:
      datasource:
        url: jdbc:mysql://localhost:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-local_dev}?useSSL=false&serverTimezone=UTC
        username: ${MYSQL_USER:-root}
        password: ${MYSQL_PASSWORD:-password}
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
          ddl-auto: validate
        show-sql: true
        properties:
          hibernate:
            format_sql: true

# Health check configuration
health_check:
  command:
    [
      "mysqladmin",
      "ping",
      "-h",
      "localhost",
      "-u",
      "${MYSQL_USER:-root}",
      "-p${MYSQL_PASSWORD:-password}",
    ]
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 30s

# Dependencies
dependencies: []

# Ports that need to be available
required_ports:
  - "${MYSQL_PORT:-3306}"

# Volume mounts
volumes:
  - name: mysql-data
    mount: /var/lib/mysql
    description: MySQL database files and data
  - name: init-scripts
    mount: /docker-entrypoint-initdb.d
    description: Database initialization scripts
    optional: true

# Web interfaces
web_interfaces: []

# Common CLI commands
cli_commands:
  connect: "docker exec -it ${PROJECT_NAME:-dev-stack}-mysql mysql -u ${MYSQL_USER:-root} -p${MYSQL_PASSWORD:-password} ${MYSQL_DATABASE:-local_dev}"
  backup: "docker exec ${PROJECT_NAME:-dev-stack}-mysql mysqldump -u ${MYSQL_USER:-root} -p${MYSQL_PASSWORD:-password} ${MYSQL_DATABASE:-local_dev} > backup.sql"
  restore: "docker exec -i ${PROJECT_NAME:-dev-stack}-mysql mysql -u ${MYSQL_USER:-root} -p${MYSQL_PASSWORD:-password} ${MYSQL_DATABASE:-local_dev} < backup.sql"

# Documentation links
docs:
  - name: MySQL Documentation
    url: https://dev.mysql.com/doc/
  - name: Spring Boot Data JPA
    url: https://docs.spring.io/spring-boot/docs/current/reference/html/data.html#data.sql.jpa-and-spring-data
  - name: Hibernate MySQL Dialect
    url: https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#database-dialect

# Common use cases
use_cases:
  - Primary application database
  - User data storage
  - Transactional data
  - Relational data modeling
  - ACID compliance requirements
  - Complex queries and joins
  - Data integrity constraints

# Integration notes
integration_notes:
  - "Requires MySQL JDBC driver in your application dependencies"
  - "DDL auto is set to 'validate' - use Flyway/Liquibase for schema management"
  - "Slow queries (>100ms) are logged for performance debugging"
  - "Default encoding is UTF-8"
  - "Connection pooling recommended for production applications"
  - "Uses MySQL 8.0 with improved performance and features"

# Required dependencies
required_dependencies:
  maven:
    - "mysql:mysql-connector-java"
  gradle:
    - "implementation 'mysql:mysql-connector-java'"

# Conflicts and warnings
conflicts:
  services:
    - postgres
  warning: "Running both MySQL and PostgreSQL simultaneously. This is unusual and may indicate configuration confusion."
