name: mysql
description: MySQL relational database for persistent data storage
category: database
version: "8"

# Default configuration
defaults:
  image: mysql:8-oracle
  port: 3306
  database: local_dev
  username: root
  password: password

# Environment variables this service provides
environment:
  MYSQL_HOST: localhost
  MYSQL_PORT: "${MYSQL_PORT:-3306}"
  MYSQL_DATABASE: "${MYSQL_DATABASE:-local_dev}"
  MYSQL_USER: "${MYSQL_USER:-root}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
  MYSQL_URL: "mysql://${MYSQL_USER:-root}:${MYSQL_PASSWORD:-password}@localhost:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-local_dev}"
  DATABASE_URL: "mysql://${MYSQL_USER:-root}:${MYSQL_PASSWORD:-password}@localhost:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-local_dev}"

# Docker-specific configuration
docker:
  restart: unless-stopped
  networks:
    - dev-stack
  memory_limit: 512m
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-password}
    - MYSQL_DATABASE=${MYSQL_DATABASE:-local_dev}
    - MYSQL_USER=${MYSQL_USER:-root}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
  health_check:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD:-password}"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 30s

# Dependencies
dependencies: []

# Ports that need to be available
required_ports:
  - "${MYSQL_PORT:-3306}"

# Volume mounts
volumes:
  - name: mysql-data
    mount: /var/lib/mysql
    description: MySQL data directory

# Documentation links
docs:
  - name: MySQL Documentation
    url: https://dev.mysql.com/doc/

# Common use cases
use_cases:
  - Primary application database
  - Transactional data storage
  - Relational data modeling
