name: "Setup Development Environment"
description: "Setup Go, install common tools, and prepare environment for dev-stack workflows"

inputs:
  install-task:
    description: "Install Task runner"
    required: false
    default: "true"
  install-tools:
    description: "Install additional tools (yq, jq)"
    required: false
    default: "false"
  cache-key-suffix:
    description: "Additional suffix for cache key"
    required: false
    default: ""

outputs:
  go-version:
    description: "The Go version that was installed"
    value: ${{ steps.setup-go.outputs.go-version }}
  task-installed:
    description: "Whether Task was installed"
    value: ${{ steps.install-task.outputs.installed }}

runs:
  using: "composite"
  steps:
    - name: Setup Go
      id: setup-go
      uses: ./.github/actions/setup-go-version

    - name: Load workflow configuration
      id: config
      shell: bash
      run: |
        if [ -f ".github/config/workflow-config.yml" ]; then
          echo "config-exists=true" >> $GITHUB_OUTPUT
        else
          echo "config-exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Install Task runner
      id: install-task
      if: inputs.install-task == 'true'
      shell: bash
      run: |
        if command -v task >/dev/null 2>&1; then
          echo "Task already installed: $(task --version)"
          echo "installed=true" >> $GITHUB_OUTPUT
        else
          echo "Installing Task runner..."
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            curl -sL https://github.com/go-task/task/releases/latest/download/task_windows_amd64.zip -o task.zip
            unzip task.zip
            mkdir -p ~/.local/bin
            mv task.exe ~/.local/bin/
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          else
            curl -sL https://taskfile.dev/install.sh | sh -s -- -d -b ~/.local/bin
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          fi
          echo "installed=true" >> $GITHUB_OUTPUT
          echo "Task installed"
        fi

    - name: Install additional tools
      if: inputs.install-tools == 'true'
      shell: bash
      run: |
        echo "Installing additional tools..."

        # Install yq
        if ! command -v yq >/dev/null 2>&1; then
          YQ_VERSION="v4.47.2"
          sudo wget -q "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          echo "yq installed: $(yq --version)"
        else
          echo "yq already installed: $(yq --version)"
        fi

        # jq is pre-installed on GitHub runners
        echo "jq version: $(jq --version)"

    - name: Download Go dependencies
      shell: bash
      run: |
        echo "Downloading Go dependencies..."
        go mod download
        go mod verify

    - name: Environment summary
      shell: bash
      run: |
        echo "🔧 Development Environment Setup Complete"
        echo "Go version: $(go version)"
        echo "Go path: $(go env GOPATH)"
        if command -v task >/dev/null 2>&1; then
          echo "Task version: $(task --version)"
        fi
        if command -v yq >/dev/null 2>&1; then
          echo "yq version: $(yq --version)"
        fi
        echo "jq version: $(jq --version)"
