name: prometheus
description: Prometheus metrics collection and monitoring system
category: observability
version: "latest"

# Default configuration
defaults:
  image: prom/prometheus:latest
  port: 9090

# Environment variables this service provides
environment:
  PROMETHEUS_HOST: localhost
  PROMETHEUS_PORT: "${PROMETHEUS_PORT:-9090}"
  PROMETHEUS_URL: "http://localhost:${PROMETHEUS_PORT:-9090}"

# Docker-specific configuration
docker:
  restart: unless-stopped
  networks:
    - dev-stack
  memory_limit: 256m
  command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--web.console.libraries=/etc/prometheus/console_libraries"
    - "--web.console.templates=/etc/prometheus/consoles"
    - "--storage.tsdb.retention.time=15d"
    - "--web.enable-lifecycle"
    - "--web.enable-admin-api"
  extra_hosts:
    - "host.docker.internal:host-gateway"
  health_check:
    test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 30s

# Spring Boot configuration
spring_config:
  properties:
    - "management.endpoints.web.exposure.include=health,info,metrics,prometheus"
    - "management.endpoint.prometheus.enabled=true"
    - "management.metrics.export.prometheus.enabled=true"

# Dependencies
dependencies: []

# Ports that need to be available
required_ports:
  - "${PROMETHEUS_PORT:-9090}"

# Volume mounts
volumes:
  - name: prometheus-data
    mount: /prometheus
    description: Prometheus data directory

# Documentation links
docs:
  - name: Prometheus Documentation
    url: https://prometheus.io/docs/

# Common use cases
use_cases:
  - Application metrics collection
  - Performance monitoring
  - Alerting and notifications
