[[main]]
  name = "Docs"
  url = "/docs/getting-started/"
  weight = 10

[[main]]
  name = "CLI Reference"
  url = "/docs/cli-reference/"
  weight = 20

[[main]]
  name = "Services"
  url = "/docs/services/"
  weight = 30

[[main]]
  name = "Contributing"
  url = "/docs/contributing/"
  weight = 40

[[social]]
  name = "GitHub"
  url = "https://github.com/isaacgarza/dev-stack"
  weight = 10
