services:
  redis:
    image: redis:7-alpine
    container_name: "${PROJECT_NAME:-local-dev}-redis"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
    command: redis-server --requirepass ${REDIS_PASSWORD:-password} --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-password}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - local-dev

volumes:
  redis-data:
    driver: local

networks:
  local-dev:
    driver: bridge
    name: "${PROJECT_NAME:-local-dev}-network"
