name: redis
description: Redis in-memory data store for caching and session storage
category: cache
version: "7"

# Default configuration
defaults:
  image: redis:7-alpine
  port: 6379
  password: password
  memory_limit: 256m
  persistence: true

# Environment variables this service provides
environment:
  REDIS_HOST: localhost
  REDIS_PORT: "${REDIS_PORT:-6379}"
  REDIS_PASSWORD: "${REDIS_PASSWORD:-password}"
  REDIS_URL: "redis://:${REDIS_PASSWORD:-password}@localhost:${REDIS_PORT:-6379}"

# Spring Boot configuration
spring_config:
  properties:
    - "spring.data.redis.host=${REDIS_HOST}"
    - "spring.data.redis.port=${REDIS_PORT}"
    - "spring.data.redis.password=${REDIS_PASSWORD}"

# Health check configuration
health_check:
  command: ["redis-cli", "-a", "${REDIS_PASSWORD:-password}", "ping"]
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 30s

# Dependencies
dependencies: []

# Ports that need to be available
required_ports:
  - "${REDIS_PORT:-6379}"

# Volume mounts
volumes:
  - name: redis-data
    mount: /data
    description: Redis persistence data

# Documentation links
docs:
  - name: Redis Documentation
    url: https://redis.io/documentation
  - name: Spring Data Redis
    url: https://docs.spring.io/spring-data/redis/docs/current/reference/html/

# Common use cases
use_cases:
  - Session storage
  - Application caching
  - Rate limiting
  - Pub/Sub messaging
  - Temporary data storage
