name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load configuration
        id: config
        uses: ./.github/actions/load-config

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          install-task: "true"

      - name: Validate Go modules
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Check formatting
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted:"
            gofmt -s -l .
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=5m

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out ./cmd/... ./internal/...

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella

      - name: Build binary
        run: task build

      - name: Verify binary
        run: |
          chmod +x ${{ steps.config.outputs.build-dir }}/${{ steps.config.outputs.cli-binary }}
          ./${{ steps.config.outputs.build-dir }}/${{ steps.config.outputs.cli-binary }} --version || \
          ./${{ steps.config.outputs.build-dir }}/${{ steps.config.outputs.cli-binary }} version || \
          echo "Binary built successfully"

  test-matrix:
    name: Test Matrix
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'test-matrix')
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ["1.21", "1.22"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race ./cmd/... ./internal/...

      - name: Build
        run: go build -o dev-stack-${{ matrix.os }}-${{ matrix.go-version }} ./cmd/dev-stack

  integration:
    name: Integration
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'integration')
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          install-task: "true"

      - name: Build binary
        run: task build

      - name: Run integration tests
        run: |
          if find ./tests -name "*_test.go" 2>/dev/null | grep -q .; then
            cd tests/integration && go test -v -tags=integration .
          else
            echo "No integration tests found, skipping..."
          fi
