name: Update Package Managers

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "Version to update in package managers"
      tag_name:
        required: true
        type: string
        description: "Git tag name for the release"

permissions:
  contents: read

jobs:
  check-config:
    name: Check Package Manager Configuration
    runs-on: ubuntu-latest
    outputs:
      homebrew_enabled: ${{ steps.config.outputs.homebrew_enabled }}
      scoop_enabled: ${{ steps.config.outputs.scoop_enabled }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Read package manager configuration
        id: config
        run: |
          CONFIG_FILE=".github/config/release-config.yaml"

          HOMEBREW_ENABLED=$(yq eval '.package_managers.homebrew.enabled' "$CONFIG_FILE")
          SCOOP_ENABLED=$(yq eval '.package_managers.scoop.enabled' "$CONFIG_FILE")

          echo "homebrew_enabled=$HOMEBREW_ENABLED" >> $GITHUB_OUTPUT
          echo "scoop_enabled=$SCOOP_ENABLED" >> $GITHUB_OUTPUT

          echo "Package manager configuration:"
          echo "  Homebrew: $HOMEBREW_ENABLED"
          echo "  Scoop: $SCOOP_ENABLED"

  package-manager-summary:
    name: Package Manager Update Summary
    runs-on: ubuntu-latest
    needs: check-config
    steps:
      - name: Summary
        run: |
          echo "📦 Package Manager Update Summary for ${{ inputs.version }}"
          echo "================================================"
          echo ""
          echo "Current Status:"
          echo "  🍺 Homebrew: ${{ needs.check-config.outputs.homebrew_enabled }}"
          echo "  🪣 Scoop: ${{ needs.check-config.outputs.scoop_enabled }}"
          echo ""

          if [[ "${{ needs.check-config.outputs.homebrew_enabled }}" == "false" ]] && [[ "${{ needs.check-config.outputs.scoop_enabled }}" == "false" ]]; then
            echo "ℹ️  No package managers are currently enabled."
            echo "   Package manager integration can be enabled in .github/config/release-config.yaml"
            echo "   when distribution through Homebrew or Scoop is desired."
          fi
